version: 2
jobs:
  fetch_and_build:
    docker:
      - image: conanio/gcc7
    steps:
      - checkout
      - run:
          name: Use Conan without modifying CMake config
          command: |
            sudo pip install --upgrade conan
            mkdir build && cd build
            conan install ..
            cmake -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake \
                -DOpenCV_DIR=$(grep -om1 '".*opencv.*"' conan_paths.cmake |sed 's/"//g')lib/ \
                ${CIRCLE_WORKING_DIRECTORY}
            cmake --build .

workflows:
  version: 2
  workflow:
    jobs:
      - fetch_and_build
