version: 2
gcc-7:
  docker:
    - image: conanio/gcc7
  steps:
    - checkout
    - run:
        name: Use Conan without modifying CMake config
        command: |
          sudo pip install --upgrade conan
          mkdir build && cd build
          conan install ..
          cmake -DCMAKE_TOOLCHIN_FILE=conan_paths.cmake ..
          cmake --build .
workflows:
  version: 2
  build_and_test:
    jobs:
      gcc-7
